# Generated by Django 4.0 on 2021-12-22 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess', models.TextField(blank=True, default='Seen', null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(blank=True, upload_to='x_files/')),
                ('video', models.FileField(blank=True, null=True, upload_to='x_files/video/')),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
