# Generated by Django 3.2.8 on 2021-10-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='mess',
            field=models.TextField(),
        ),
    ]
