# Generated by Django 3.2.8 on 2021-10-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_mess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='mess',
            field=models.CharField(max_length=1000),
        ),
    ]
