# Generated by Django 3.2.8 on 2021-10-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chat_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='mess',
            field=models.CharField(blank=True, default='Seen', max_length=1000, null=True),
        ),
    ]
