# Generated by Django 3.2.8 on 2021-10-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20211026_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='file',
            field=models.FileField(default=1, upload_to='file/'),
            preserve_default=False,
        ),
    ]
