# Generated by Django 3.2.8 on 2021-10-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_chat_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='file',
            field=models.ImageField(blank=True, upload_to='x_files/'),
        ),
    ]
