# Generated by Django 3.2.8 on 2021-10-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_senderuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='x_files/video/'),
        ),
        migrations.DeleteModel(
            name='senderuser',
        ),
    ]
